### ISSUE TITLE
Weekly recurring event does not return first date

### ISSUE THREAD

**Issue by tkortekaas** [hnvcam/teno_rrule#1]
Given the following example, where I want to have an event repeat every Friday of the week, starting from 2024-03-20.
Note: 2024-03-20 is a Wednesday.
I would expect the first occurrence of this event to happen on the first Friday, so 2024-03-22, however this does not happen.

Example code:
`RecurrenceRule tester = RecurrenceRule.from('RRULE:FREQ=WEEKLY;BYDAY=FR')!.copyWith(startDate: DateTime.utc(2024, 03, 20));
    print(tester.allInstances);`

Output:
`I/flutter (10045): [2024-03-29 00:00:00.000, 2024-04-05 01:00:00.000, 2024-04-12 01:00:00.000, 2024-04-19 01:00:00.000, 2024-04-26 01:00:00.000, 2024-05-03 01:00:00.000, 2024-05-10 01:00:00.000, 2024-05-17 01:00:00.000, 2024-05-24 01:00:00.000, 2024-05-31 01:00:00.000, 2024-06-07 01:00:00.000, 2024-06-14 01:00:00.000, 2024-06-21 01:00:00.000, 2024-06-28 01:00:00.000, 2024-07-05 01:00:00.000, 2024-07-12 01:00:00.000, 2024-07-19 01:00:00.000, 2024-07-26 01:00:00.000, 2024-08-02 01:00:00.000, 2024-08-09 01:00:00.000, 2024-08-16 01:00:00.000, 2024-08-23 01:00:00.000, 2024-08-30 01:00:00.000, 2024-09-06 01:00:00.000, 2024-09-13 01:00:00.000, 2024-09-20 01:00:00.000, 2024-09-27 01:00:00.000, 2024-10-04 01:00:00.000, 2024-10-11 01:00:00.000, 2024-10-18 01:00:00.000, 2024-10-25 01:00:00.000, 2024-11-01 00:00:00.000, 2024-11-08 00:00:00.000, 2024-11-15 00:00:00.000, 2024-11-22 00:00:00.000, 2024-11-29 00:00:00.000, 2024-12-06 00:00:00.000, 2024-12-13 00:00:00.000, 2024-12-20 00:00:00.000, 2024-12-27 00:00:00.000, 2026-01-03 00:00:00.00`

Is this an error in the package or is this intended behaviour?

**Comment by hnvcam** [comment]
Hey, 
Thank you for reporting this bug. I've fixed it. Please use the latest version.
Cheers,
Cam

**Comment by tkortekaas** [comment]
Haha just saw the fix, I didn't expect it to be a utc datetime issue. Thank you for resolving it!
