### ISSUE TITLE
Generate convertion wrong

### ISSUE THREAD

**Issue by rahmanrezaee** [hnvcam/teno_rrule#3]
**Issue:**
Incorrect dates generated for the recurrence rule:

**Recurrence Rule:**
```
FREQ=WEEKLY;BYDAY=FR,SA;INTERVAL=1;COUNT=10
```

**Start Date:**
```
2024-12-20 16:00:00.000
```

**Expected Dates:**
The recurrence rule specifies weekly events on Fridays (FR) and Saturdays (SA) starting from the given start date, with a total count of 10 events. The expected dates are:
```
2024-12-20 16:00:00.000, 2024-12-21 16:00:00.000, 2024-12-27 16:00:00.000, 2024-12-28 16:00:00.000,
2025-01-03 16:00:00.000, 2025-01-04 16:00:00.000, 2025-01-10 16:00:00.000, 2025-01-11 16:00:00.000,
2025-01-17 16:00:00.000, 2025-01-18 16:00:00.000
```

**Generated Dates:**
```
2024-12-20 16:00:00.000, 2024-12-21 16:00:00.000, 2024-12-27 16:00:00.000, 2024-12-28 16:00:00.000,
2026-01-03 16:00:00.000, 2026-01-04 16:00:00.000, 2025-01-10 16:00:00.000, 2025-01-11 16:00:00.000,
2025-01-17 16:00:00.000, 2025-01-18 16:00:00.000
```

**Problematic Dates:**
1. **2026-01-03 16:00:00.000**
2. **2026-01-04 16:00:00.000**

These dates are incorrect as they do not align with the recurrence rule's constraints. The rule should only generate dates for Fridays and Saturdays within the defined interval.

**Steps to Reproduce:**
1. Use the recurrence rule `FREQ=WEEKLY;BYDAY=FR,SA;INTERVAL=1;COUNT=10`.
2. Set the start date as `2024-12-20 16:00:00.000`.
3. Generate the recurrence dates.

**Expected Outcome:**
The generated dates should strictly follow the `BYDAY` parameter (Fridays and Saturdays) and respect the `COUNT` limit.

**Actual Outcome:**
Dates outside the defined days and interval (e.g., **2026-01-03** and **2026-01-04**) are included in the results.

**Suggested Fix:**
Investigate the recurrence logic, particularly:
- Validation of the `BYDAY` parameter.
- Correct application of the `COUNT` limit.

Ensure the generation logic does not skip over or misinterpret the specified days or intervals.

**Comment by hnvcam** [comment]
Hi,

Thank you for your detailed bug report.

The issue was caused by a missing year clone when constructing the next instance in the ByWeekDaysHandler. Because the start of the week for 2025-01-03 is in the previous year, the missing year copy caused the instance to shift to 2026, as you discovered.

This has now been fixed, and I've added tests to prevent regressions.

Thank you again for your contribution to the library.

Cheers,
Cam
